### ISSUE TITLE
"Array to string conversion" in PHP proxy classes

### ISSUE THREAD

**Issue by AlexanderKarpanProdege** [51Degrees/device-detection-php-onpremise#13]
We keep getting "Array to string conversion" exception at this place (in a percent of cases):
```php
/* PHP Proxy Classes */
class MapStringStringSwig {
//...
    function set($key,$x) {
	MapStringStringSwig_set($this->_cPtr,$key,$x);  // here
    }
//...
}
```

Once there was a user agent string which was triggering it, but that time updating the database helped.

One of the recent exceptions happened for a visitor with this user agent: "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36". The device detection works well on the string alone, so I assume the problem could be because of the HTTP headers of that visitor.

Any suggestions?

**Comment by AlexanderKarpanProdege** [comment]
Hi Kirstin!

Thanks for the reply!

1. From php.ini :
```
extension=FiftyOneDegreesHashEngine.so
FiftyOneDegreesHashEngine.performance_profile=MaxPerformance
FiftyOneDegreesHashEngine.data_file=/usr/local/lib/Enterprise-HashV41.hash
```

2. The top of the stacktrace:
```
app/AdGateMedia/Infrastructure/FiftyOneDegrees/FiftyOneDegreesHashEngine.php:63
vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:250
???:0
app/AdGateMedia/Infrastructure/FiftyOneDegrees/FiftyOneDegreesHashEngine.php:63
app/AdGateMedia/Infrastructure/FiftyOneDegrees/DeviceDetectionOnPremiseEngine.php:95
vendor/51degrees/fiftyone.pipeline.engines/Engine.php:98
vendor/51degrees/fiftyone.pipeline.core/FlowData.php:68
app/AdGateMedia/Infrastructure/FiftyOneDegrees/DeviceDetectionService.php:64
app/AdGateMedia/Infrastructure/FiftyOneDegrees/DeviceDetectionService.php:20
// our app code
// Laravel 10 code
```

Also, this is an excerpt from 'composer info' with actual versions :
```
51degrees/fiftyone.devicedetection             4.4.2     Device detection engines for 51Degrees Pipeline API - Get hardware and software details of the dev...
51degrees/fiftyone.pipeline.cloudrequestengine 4.4.2     Cloud request engine for 51Degrees Pipeline API - Used to send requests to the 51Degrees cloud ser...
51degrees/fiftyone.pipeline.core               4.4.2     51Degrees Pipeline API - Real-time data micro-services aggregator.
51degrees/fiftyone.pipeline.engines            4.4.2     Engines shared functionality library for 51Degrees Pipeline API
```

3. I will try to get you the value of $key which causes the exception soon.


Thanks again,
Alexander

**Comment by AlexanderKarpanProdege** [comment]
You may need to see a piece of `app/AdGateMedia/Infrastructure/FiftyOneDegrees/DeviceDetectionOnPremiseEngine.php`:
(lines 87-103)
```php
    public function processInternal($flowData)
    {
        // Make evidence collection
        $evidence = $flowData->evidence->getAll();

        $evidenceInternal = new EvidenceDeviceDetectionSwig();

        foreach ($evidence as $key => $value) {
            $evidenceInternal->set($key, $value);   // line 95 from the stacktrace
        }

        $result = $this->engine->process($evidenceInternal);

        $data = new SwigData($this, $result);

        $flowData->setElementData($data);
    }
```

Hope it helps!

**Comment by kirstin51D** [comment]
Amazing, thanks for this info! As soon as you get the value of the $key, do let me know. We have a theory on what's causing the issue, but need the value to be able to confirm. Thanks :)

**Comment by AlexanderKarpanProdege** [comment]
Hey!
This is what I've just got:
```json
{
    "key": "query.categories",
    "x":
    [
        "1",
        "10",
        "11"
    ],
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "headers":
    {
        "cf-ipcountry": "US",
        "cf-connecting-ip": "2a0d:5600:6:b003::1d2b",
        "cdn-loop": "cloudflare",
        "accept-language": "en-US,en;q=0.9,fa;q=0.8",
        "referer": "https://example.org?age=&gender=&categories=1,10,11",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "sec-ch-ua-platform": "\"Windows\"",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
        "sec-ch-ua-mobile": "?0",
        "x-requested-with": "XMLHttpRequest",
        "accept": "application/json, text/plain, */*",
        "sec-ch-ua": "\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\"",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "cf-ray": "7e691a770aa90335-SEA",
        "accept-encoding": "gzip",
        "x-amzn-trace-id": "Root=1-64b1244b-45533a142fb4a285694393a5",
        "host": "example.org",
        "x-forwarded-port": "80",
        "x-forwarded-proto": "http",
        "x-forwarded-for": "2a0d:5600:6:b003::1d2b, 172.71.142.167",
        "content-length": "",
        "content-type": ""
    }
}
```
(I only replaced the domain name with 'example.org')

So apparently it takes the comma-separate 'categories' from the query and turns it into an array.

**Comment by AlexanderKarpanProdege** [comment]
Oh, in fact the URL is like this: `https://example.org?android_id=&ios_id=&categories%5B0%5D=1&categories%5B1%5D=10&categories%5B2%5D=11&ua=&mfg=&offer_events=1`
So 'categories[]' in the URL is what triggers the exception.

**Comment by AlexanderKarpanProdege** [comment]
On a separate note: we have this line:
```php
$data->evidence->setFromWebRequest($headers, [], []);
```

But in `vendor/51degrees/fiftyone.pipeline.core/Evidence.php` it's like that:
```php
public function setFromWebRequest($server = null, $cookies = null, $query = null)
{
        if (!$server) {
            $server = $_SERVER;
        }

        if (!$cookies) {
            $cookies = $_COOKIE;
        }

        if (!$query) {
            $query = $_GET;
        }
        //...
}
```

This is how the GET parameters leaked into the device detection. Sometimes we run the device detection from CLI commands (we feed it user agents stored in our database), also in tests I believe $_GET is not set properly. Could you update this function to check against 'null' instead?
```php
if ($query === null) {
    $query = $_GET;
}
```

**Comment by Sara51D** [comment]
Hi @AlexanderKarpanProdege 
Thank you for sharing this information, we are looking into this issue and will get back to you soon,

**Comment by jwrosewell** [comment]
These two PRs relate to this issue and also provide general improvements to performance.

https://github.com/51Degrees/device-detection-php-onpremise/pull/16
https://github.com/51Degrees/pipeline-php-core/pull/7

@AlexanderKarpanProdege the modifications are simple so please try them ahead of the PRs being peer reviewed and testing completed.

**Comment by AlexanderKarpanProdege** [comment]
@jwrosewell I tried both changes.
There is still an issue "Array to string conversion" here: `"vendor/51degrees/fiftyone.pipeline.core/Evidence.php:124"`

```php
        foreach ($query as $key => $value) {
            error_log("query." . $key . ": " . $value, 0);
            $evidence["query." . $key] = $value;
        }
```
triggered by a URL `https://example.org?s2=fc392fea&s3=&s4=&s5=&android_id=&ios_id=&categories%5B0%5D=13&ua=&mfg=&offers=%5B%7B%22id%22:%22402471%22,%22position%22:7%7D,%7B%22id%22:%22669538%22,%22position%22:6%7D%5D`

**Comment by jwrosewell** [comment]
Thanks. I've now removed the error_log statements which were left in by mistake. See the cleaned up file [here](https://github.com/51Degrees/pipeline-php-core/blob/feature/evidence-performance/Evidence.php).

My colleague @ben51degrees will review the PR tomorrow and perform additional peer review.

**Comment by ben51degrees** [comment]
@jwrosewell , @AlexanderKarpanProdege ,
I've reviewed those pull requests and approved. So these should be automatically tested and released this eveneing.

**Comment by ben51degrees** [comment]
Both these PRs have now been merged, so I will close this issue.
If this is still a problem, feel free to repoen this issue.
