### ISSUE TITLE
Unable to install on Alpine

### ISSUE THREAD

**Issue by Ryan-Jung** [51Degrees/device-detection-php-onpremise#7]
On Alpine 3.13 `make` command threw error `make: *** [Makefile:334: FiftyOneDegreesHashEngine.la] Error 1`

This was on a docker container using `alpine:3.13`

Package information:
- g++-10.2.1_pre1-r3
- php7-7.4.28-r0
- make-4.3-r0
- php7-dev-7.4.28-r0

Attached console output starting from the ./configure step
[install_output_alpine_3.13.txt](https://github.com/51Degrees/device-detection-php-onpremise/files/8302190/install_output_alpine_3.13.txt)

**Comment by tungntpham** [comment]
Hi @Ryan-Jung,

Many thanks for raising this issue. We have reviewed and have identified that this is to do with the new version of gcc. We have mainly tested with gcc 7.5 so you can try to install gcc 7.5 and see if it works for you.

We are currently tracking this issue [here](https://github.com/51Degrees/common-cxx/issues/6)

We will make changes to address this issue and will keep you updated.

Many thanks,
Tung.

**Comment by tungntpham** [comment]
Hi @Ryan-Jung,

This issue is now resolved in the 4.4.2 version. Please feel free to reopen this if it is not resolved for you.

Kind regards,
Tung.
